In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from matplotlib import font_manager, rc

In [2]:
# 한글 폰트 설정
font_path = "C:/Windows/Fonts/malgun.ttf"  # 사용하고 있는 OS에 맞는 한글 폰트 경로로 수정해주세요.
font_name = font_manager.FontProperties(fname=font_path).get_name()
rc('font', family=font_name)

In [35]:
solar = pd.read_csv('solar_rf.csv')
wind = pd.read_csv('wind_rf.csv')

In [36]:
solar

             일시     태양광전체  일조(hr)  일사(MJ/m2)          예측값
0    2022-01-01  5141.272    0.66       0.99  6319.404046
1    2022-01-02  2238.776    0.48       0.54  3206.278891
2    2022-01-03  4532.312    0.69       0.98  6603.905013
3    2022-01-04  1210.208    0.41       0.46  3297.440281
4    2022-01-05   403.656    0.00       0.09   533.718156
..          ...       ...     ...        ...          ...
725  2023-12-27  6165.104    0.56       0.88  6787.405926
726  2023-12-28  4882.013    0.50       0.89  4065.575254
727  2023-12-29  6737.501    0.40       0.79  4863.085064
728  2023-12-30  6650.564    0.50       0.87  4623.058842
729  2023-12-31  1687.698    0.16       0.33  2398.035507

[730 rows x 5 columns]

In [37]:
wind

             일시         실제값   랜덤 포레스트 예측값
0    2022-01-01  190443.180  209490.02754
1    2022-01-02  267382.380  261177.85943
2    2022-01-03  261493.740  232387.32327
3    2022-01-04  343960.380  309494.80817
4    2022-01-05  147205.620  154669.51740
..          ...         ...           ...
725  2023-12-27   30888.960   43323.07280
726  2023-12-28   92603.340   81793.23703
727  2023-12-29  214559.833  192637.69805
728  2023-12-30   27898.038   52833.28579
729  2023-12-31  754356.353  752551.12525

[730 rows x 3 columns]

## 태양광 탄소 배출량

In [38]:
# 발전량 차이 계산
solar['발전량 차이'] = solar['예측값'] - solar['태양광전체']

# 탄소 배출량 감소 비율 계산
solar['탄소 배출량 감소 비율'] = (solar['발전량 차이'] / solar['태양광전체']) * 16.8

In [39]:
solar = solar.drop(columns=[ '일조(hr)', '일사(MJ/m2)'])

In [40]:
solar

             일시     태양광전체          예측값       발전량 차이  탄소 배출량 감소 비율
0    2022-01-01  5141.272  6319.404046  1178.132046      3.849751
1    2022-01-02  2238.776  3206.278891   967.502891      7.260239
2    2022-01-03  4532.312  6603.905013  2071.593013      7.678810
3    2022-01-04  1210.208  3297.440281  2087.232281     28.974773
4    2022-01-05   403.656   533.718156   130.062156      5.413134
..          ...       ...          ...          ...           ...
725  2023-12-27  6165.104  6787.405926   622.301926      1.695782
726  2023-12-28  4882.013  4065.575254  -816.437746     -2.809528
727  2023-12-29  6737.501  4863.085064 -1874.415936     -4.673868
728  2023-12-30  6650.564  4623.058842 -2027.505158     -5.121684
729  2023-12-31  1687.698  2398.035507   710.337507      7.070975

[730 rows x 5 columns]

In [41]:
# 전체 실제 발전량의 총합
total_actual_generation = solar['태양광전체'].sum()

# 전체 예측된 발전량의 총합
total_predicted_generation = solar['예측값'].sum()

# 발전량 차이
generation_difference = total_predicted_generation - total_actual_generation

# 발전량 증가 비율
increase_ratio = generation_difference / total_actual_generation

# 탄소 배출량 감소 비율
carbon_emission_reduction_ratio = increase_ratio * 16.8

# 결과 출력
print(f"전체 실제 발전량: {total_actual_generation:.2f}")
print(f"전체 예측된 발전량: {total_predicted_generation:.2f}")
print(f"발전량 차이: {generation_difference:.2f}")
print(f"탄소 배출량 감소 비율: {carbon_emission_reduction_ratio:.2f}%")

전체 실제 발전량: 4007946.38
전체 예측된 발전량: 3723911.20
발전량 차이: -284035.18
탄소 배출량 감소 비율: -1.19%

## 풍력 탄소 배출량

In [42]:
# 발전량 차이 계산
wind['발전량 차이'] = wind['랜덤 포레스트 예측값'] - wind['실제값']

# 탄소 배출량 감소 비율 계산
wind['탄소 배출량 감소 비율'] = (wind['발전량 차이'] / wind['실제값']) * 16.8

In [43]:
wind

             일시         실제값   랜덤 포레스트 예측값       발전량 차이  탄소 배출량 감소 비율
0    2022-01-01  190443.180  209490.02754  19046.84754      1.680223
1    2022-01-02  267382.380  261177.85943  -6204.52057     -0.389838
2    2022-01-03  261493.740  232387.32327 -29106.41673     -1.869979
3    2022-01-04  343960.380  309494.80817 -34465.57183     -1.683396
4    2022-01-05  147205.620  154669.51740   7463.89740      0.851825
..          ...         ...           ...          ...           ...
725  2023-12-27   30888.960   43323.07280  12434.11280      6.762711
726  2023-12-28   92603.340   81793.23703 -10810.10297     -1.961157
727  2023-12-29  214559.833  192637.69805 -21922.13495     -1.716500
728  2023-12-30   27898.038   52833.28579  24935.24779     15.015829
729  2023-12-31  754356.353  752551.12525  -1805.22775     -0.040204

[730 rows x 5 columns]

In [44]:
# 전체 실제 발전량의 총합
total_actual_generation = wind['실제값'].sum()

# 전체 예측된 발전량의 총합
total_predicted_generation = wind['랜덤 포레스트 예측값'].sum()

# 발전량 차이
generation_difference = total_predicted_generation - total_actual_generation

# 발전량 증가 비율
increase_ratio = generation_difference / total_actual_generation

# 탄소 배출량 감소 비율
carbon_emission_reduction_ratio = increase_ratio * 16.8

# 결과 출력
print(f"전체 실제 발전량: {total_actual_generation:.2f}")
print(f"전체 예측된 발전량: {total_predicted_generation:.2f}")
print(f"발전량 차이: {generation_difference:.2f}")
print(f"탄소 배출량 감소 비율: {carbon_emission_reduction_ratio:.2f}%")

전체 실제 발전량: 175505276.27
전체 예측된 발전량: 175962288.02
발전량 차이: 457011.75
탄소 배출량 감소 비율: 0.04%

## 태양광 정산단가

In [45]:
money = pd.read_csv('정산단가.csv')

In [46]:
money = money[['기간','신재생_태양','신재생_풍력']]

In [47]:
money['일시']=money['기간']

In [48]:
money = money[['일시','신재생_태양','신재생_풍력']]

In [49]:
money

             일시      신재생_태양      신재생_풍력
0    2022-01-01  149.903263  161.324304
1    2022-01-02  149.903263  161.324304
2    2022-01-03  149.903263  161.324304
3    2022-01-04  149.903263  161.324304
4    2022-01-05  149.903263  161.324304
..          ...         ...         ...
725  2023-12-27  140.354227  128.723727
726  2023-12-28  140.354227  128.723727
727  2023-12-29  140.354227  128.723727
728  2023-12-30  140.354227  128.723727
729  2023-12-31  140.354227  128.723727

[730 rows x 3 columns]

In [50]:
# 데이터프레임 병합 (기간 기준)
merged_df = pd.merge(money, solar, on = "일시")

# 태양광 발전량에 따른 총 가격 계산 (실제값과 예측값 각각에 대해)
merged_df['실제값_태양_가격'] = merged_df['태양광전체'] * merged_df['신재생_태양']
merged_df['예측값_태양_가격'] = merged_df['예측값'] * merged_df['신재생_태양']

# 가격 차이 계산
merged_df['태양_가격 차이'] = merged_df['예측값_태양_가격'] - merged_df['실제값_태양_가격']

# 전체 실제 발전량과 예측 발전량의 총 가격 계산
total_actual_solar_price = merged_df['실제값_태양_가격'].sum()
total_predicted_solar_price = merged_df['예측값_태양_가격'].sum()
total_solar_price_difference = total_predicted_solar_price - total_actual_solar_price

# 결과 출력
print(merged_df[['일시', '태양광전체', '예측값', '실제값_태양_가격', '예측값_태양_가격', '태양_가격 차이']])
print(f"전체 실제 태양광 발전량 총 가격: {total_actual_solar_price:.2f}")
print(f"전체 예측된 태양광 발전량 총 가격: {total_predicted_solar_price:.2f}")
print(f"총 태양광 가격 차이: {total_solar_price_difference:.2f}")

             일시     태양광전체          예측값      실제값_태양_가격      예측값_태양_가격  \
0    2022-01-01  5141.272  6319.404046  770693.449285  947299.287404
1    2022-01-02  2238.776  3206.278891  335599.827750  480631.668205
2    2022-01-03  4532.312  6603.905013  679408.358187  989946.910667
3    2022-01-04  1210.208  3297.440281  181414.128230  494297.057993
4    2022-01-05   403.656   533.718156   60509.351570   80006.093087
..          ...       ...          ...            ...            ...
725  2023-12-27  6165.104  6787.405926  865298.406295  952641.112142
726  2023-12-28  4882.013  4065.575254  685211.160819  570620.672034
727  2023-12-29  6737.501  4863.085064  945636.744767  682554.545025
728  2023-12-30  6650.564  4623.058842  933434.769334  648865.850101
729  2023-12-31  1687.698  2398.035507  236875.548199  336574.419840

          태양_가격 차이
0    176605.838119
1    145031.840455
2    310538.552480
3    312882.929764
4     19496.741517
..             ...
725   87342.705847
726 -114590.488785
727 -263082.199741
728 -284568.919233
729   99698.871641

[730 rows x 6 columns]
전체 실제 태양광 발전량 총 가격: 686372438.56
전체 예측된 태양광 발전량 총 가격: 649136044.85
총 태양광 가격 차이: -37236393.71

In [55]:
# '일시' 열을 datetime 형식으로 변환
merged_df['일시'] = pd.to_datetime(merged_df['일시'])

# 월별로 그룹화
merged_df['월'] = merged_df['일시'].dt.to_period('M')

# 월별 총 가격 계산
monthly_summary = merged_df.groupby('월').agg(
    실제값_태양_총가격=('실제값_태양_가격', 'sum'),
    예측값_태양_총가격=('예측값_태양_가격', 'sum')
).reset_index()

# 가격 차이 계산
monthly_summary['태양_가격_차이'] = monthly_summary['예측값_태양_총가격'] - monthly_summary['실제값_태양_총가격']
# 소수점 두 자리까지 표시 설정
pd.options.display.float_format = '{:.2f}'.format

In [56]:
monthly_summary

          월  실제값_태양_총가격  예측값_태양_총가격     태양_가격_차이
0   2022-01 13690745.37 16831146.00   3140400.63
1   2022-02 20932394.73 22462366.54   1529971.81
2   2022-03 28824602.81 30589986.59   1765383.78
3   2022-04 33214313.87 37359778.89   4145465.02
4   2022-05 22824420.21 24705997.83   1881577.62
5   2022-06 17432359.20 19251948.57   1819589.37
6   2022-07 21828642.74 25131124.17   3302481.44
7   2022-08 32097117.26 36021890.14   3924772.88
8   2022-09 24151509.58 29833578.53   5682068.95
9   2022-10 33964048.06 39702906.68   5738858.62
10  2022-11 22784750.88 29680874.97   6896124.08
11  2022-12 10972094.87 12692948.10   1720853.23
12  2023-01 24614515.56 20785922.62  -3828592.93
13  2023-02 32633223.44 27092601.56  -5540621.88
14  2023-03 58488327.42 48208063.89 -10280263.53
15  2023-04 42067351.43 33819717.96  -8247633.47
16  2023-05 30460788.38 27470495.79  -2990292.59
17  2023-06 35160042.91 23943679.32 -11216363.60
18  2023-07 33757618.12 23261820.58 -10495797.54
19  2023-08 40094029.00 32493380.31  -7600648.68
20  2023-09 32148598.61 28298452.68  -3850145.92
21  2023-10 34610497.39 29311845.33  -5298652.06
22  2023-11 23679599.89 18043576.07  -5636023.82
23  2023-12 15940846.84 12141941.72  -3798905.12

## 풍력 정산단가

In [59]:
# 데이터프레임 병합 (기간 기준)
merged_df = pd.merge(money, wind, on = "일시")

# 태양광 발전량에 따른 총 가격 계산 (실제값과 예측값 각각에 대해)
merged_df['실제값_풍력_가격'] = merged_df['실제값'] * merged_df['신재생_풍력']
merged_df['예측값_풍력_가격'] = merged_df['랜덤 포레스트 예측값'] * merged_df['신재생_풍력']

# 가격 차이 계산
merged_df['풍력_가격 차이'] = merged_df['예측값_풍력_가격'] - merged_df['실제값_풍력_가격']

# 전체 실제 발전량과 예측 발전량의 총 가격 계산
total_actual_wind_price = merged_df['실제값_풍력_가격'].sum()
total_predicted_wind_price = merged_df['예측값_풍력_가격'].sum()
total_wind_price_difference = total_predicted_solar_price - total_actual_solar_price

# 결과 출력
print(f"전체 실제 풍력 발전량 총 가격: {total_actual_wind_price:.2f}")
print(f"전체 예측된 풍력 발전량 총 가격: {total_predicted_wind_price:.2f}")
print(f"총 풍력 가격 차이: {total_wind_price_difference:.2f}")

전체 실제 풍력 발전량 총 가격: 30187151244.30
전체 예측된 풍력 발전량 총 가격: 30340381383.32
총 풍력 가격 차이: -37236393.71

In [60]:
# '일시' 열을 datetime 형식으로 변환
merged_df['일시'] = pd.to_datetime(merged_df['일시'])

# 월별로 그룹화
merged_df['월'] = merged_df['일시'].dt.to_period('M')

# 월별 총 가격 계산
monthly_summary = merged_df.groupby('월').agg(
    실제값_풍력_총가격=('실제값_풍력_가격', 'sum'),
    예측값_풍력_총가격=('예측값_풍력_가격', 'sum')
).reset_index()

# 가격 차이 계산
monthly_summary['풍력_가격_차이'] = monthly_summary['예측값_풍력_총가격'] - monthly_summary['실제값_풍력_총가격']
# 소수점 두 자리까지 표시 설정
pd.options.display.float_format = '{:.2f}'.format

In [61]:
monthly_summary

          월    실제값_풍력_총가격    예측값_풍력_총가격     풍력_가격_차이
0   2022-01 2003420227.33 1931182045.13 -72238182.20
1   2022-02 2424176062.94 2395544858.99 -28631203.95
2   2022-03 1751031755.99 1693725049.56 -57306706.43
3   2022-04  972873144.69 1007753049.00  34879904.31
4   2022-05  685142168.29  672758908.95 -12383259.33
5   2022-06  879193166.77  858427579.26 -20765587.51
6   2022-07  925342840.85  881116113.07 -44226727.78
7   2022-08  723979617.09  865524998.67 141545381.58
8   2022-09 1645460151.30 1687387273.00  41927121.70
9   2022-10 2079092327.63 2142788818.13  63696490.51
10  2022-11 1706940549.06 1657054835.37 -49885713.69
11  2022-12 2022759499.08 2118556117.28  95796618.20
12  2023-01 1804070325.68 1803672115.09   -398210.59
13  2023-02 1222393009.88 1201678223.57 -20714786.31
14  2023-03 1076940916.08 1145885637.15  68944721.08
15  2023-04 1345660389.12 1398018314.13  52357925.01
16  2023-05  904289707.02  869186553.38 -35103153.64
17  2023-06  574086942.08  615937542.28  41850600.20
18  2023-07  826115509.12  852228539.00  26113029.88
19  2023-08  665838988.15  662618462.43  -3220525.72
20  2023-09  520095820.63  530389486.65  10293666.02
21  2023-10  885241871.90  814025003.08 -71216868.82
22  2023-11 1261569562.59 1218605600.73 -42963961.86
23  2023-12 1281436691.04 1316316259.42  34879568.39